### ISSUE TITLE
Cobbled Deepslate?

### ISSUE THREAD

**Issue by Venaf** [MrLoLf/compblocks#1]
We have Deepslate as an option, but could Cobbled Deepslate be added to the compressible blocks? I hardly ever mine deepslate with silk touch since it's normally useless in the raw form.

**Comment by MrLoLf** [comment]
I will try to add this in the future, right now I'm quite busy.

**Comment by MrLoLf** [comment]
I have added Cobbled Deepslate. Thank you for your suggestion. I will close the issue now, due to the new feature implemented.
