### ISSUE TITLE
Strange anomoly.

### ISSUE THREAD

**Issue by KaZAamM** [MrLoLf/compblocks#3]
Hello, love your compressed blocks but there is an unusual issue with the Birch compressed blocks. 5X breaks down to 4X. Good. 4X breaks back to 5X. 3X breaks down to 4X instead of 2X. 2X breaks down to 1X, normal.

I went through the entire lot of compressed blocks to search for any other problems. None other found. Everything works properly except for Birch. I tried repeating this many times and the same results take place.

Excellent mod otherwise.

KaZ...

**Comment by MrLoLf** [comment]
I've probably messed something up in the recipes .json of birch thanks for the report, will fix this when I find time for it.
These are the files with the wrong nuber in it https://github.com/MrLoLf/compblocks/blob/1.20/src/main/resources/data/compressedblocks/recipes/birchuncraftx3.json and https://github.com/MrLoLf/compblocks/blob/1.20/src/main/resources/data/compressedblocks/recipes/birchuncraftx4.json

**Comment by KaZAamM** [comment]
Thank you for fixing the Birch compressed blocks! Just noticed that you took out the compressed Netherite blocks. Was this intentional? They're unbelievably difficult to obtain anyways, can't even imagine trying to find enough netherite to make a 1X compressed block doing it the hard way. lol

**Comment by MrLoLf** [comment]
No I didn't remove them. You can see my changes in the commits I made. Maybe there was an bug with the commits and versions I'll add it back for 1.17. did this happen to other versions too?

**Comment by MrLoLf** [comment]
It looks like 1.17.x and 1.20.x are having netherite remove I've readded it for 1.17.x. 1.20.x will follow now thanks for the report of this mistake. It should be fixed now pls let me know if you find anything else and open a new issue for it. Thanks a lot.
