### ISSUE TITLE
Add Compatibility with O' The Biomes You Will Go's Blocks such as the Dacite Variant of Cobblestone [Feature Request]

### ISSUE THREAD

**Issue by wereretot** [MrLoLf/compblocks#6]
It is quite frustrating to not be able to compress this variant of cobblestone since I'm in a biome with so much of it.

**Comment by MrLoLf** [comment]
I'll add this in a few weeks, when I'm done with my exams this semester. This should be an easy fix, but for uncrafting it will always become normal cobblestone, as I'm not allowed to have multiple options like tags used for crafting an item.
